### ISSUE TITLE
refactoring needed: unmarshalField is getting too complicated

### ISSUE THREAD

**Issue by ccoVeille** [syntaqx/env#10]
It's getting too complicated, it was OK when you had 2 fields

you should define a struct with all the fields you need, then create a variable from this struct, then pass a reference to the variable and, that's it

No more code rewrites when adding a new feature, and also less pointers

_Originally posted by @ccoVeille in https://github.com/syntaqx/env/pull/9#discussion_r1682434216_

**Comment by syntaqx** [comment]
I'm not sure I fully understand this issue. There's a tag options struct that has everything layed out cleanly, and while the reverse lookup for defaults is complex, everything is working and the different usage values are optional

**Comment by syntaqx** [comment]
I could see a way to refactor this to make it less intense in that I populate all tags that are not expanded variables first, then populate expanded variables afterwards.

That might help with simplifying the pointer logic that I think you're not a fan of. However, I do this what I have is likely the most efficient?

**Comment by ccoVeille** [comment]
I'm in holidays, without computer and with limited and sporadic internet connection.

I'll give you a feedback about the struct idea I had in about a week.

**Comment by ccoVeille** [comment]
I was busy. I'm sorry.

My remark in the PR was not important.

It's OK to close this issue.
