### ISSUE TITLE
Are you open for code review?

### ISSUE THREAD

**Issue by ccoVeille** [syntaqx/env#4]
I started looking at your lib, and I'm facing some design issues

**Comment by ccoVeille** [comment]
Let me start

I don't expect a lib to proxify `os` package

I would remove all this

```go
// Set sets an environment variable.
func Set(key, value string) error {
        return os.Setenv(key, value)
}

// Unset unsets an environment variable.
func Unset(key string) error {
        return os.Unsetenv(key)
}

// Lookup returns the value of an environment variable and a boolean indicating
// whether the variable is present in the environment.
func Lookup(key string) (string, bool) {
        return os.LookupEnv(key)
}

// Get returns the value of an environment variable.
func Get(key string) string {
        return os.Getenv(key)
}
```

**Comment by ccoVeille** [comment]
I disagree with your *WithFallback helper.

Returning the fallback method when the env variable is expected, so you should always use Lookup, then call the method you are fallback.

Bit I disagree with the fallback on any other error.

Is someone provide "foo" in an env variable that is supposed to be a float, the code should know there is an error

You should always return an error in the methods signature

You may return the fallback value on error, but there should be a clear error returned

**Comment by ccoVeille** [comment]
All your assert* helper defined in env_test.go must have a `t.Helper()` call

**Comment by ccoVeille** [comment]
About this

```go
type DatabaseConfig struct {
        Host     string       `env:"DATABASE_HOST,default=localhost"`
        Port     int          `env:"DATABASE_PORT|DB_PORT,fallback=3306"`
        Username string       `env:"DATABASE_USERNAME,default=root"`
        Password string       `env:"DATABASE_PASSWORD,required"`
        Database string       `env:"DATABASE_NAME"`
        Nested   NestedConfig `env:""`
}

type Config struct {
        Debug     bool           `env:"DEBUG"`
        Port      string         `env:"PORT,default=8080"`
        RedisHost []string       `env:"REDIS_HOST|REDIS_HOSTS,default=localhost:6379"`
        RedisMode RedisMode      `env:"REDIS_MODE,default=standalone"`
        Database  DatabaseConfig `env:""`
}
```

I would expect the config to define the database prefix

```go
type DatabaseConfig struct {
        Host     string       `env:"HOST,default=localhost"`
        Port     int          `env:"PORT|DB_PORT,fallback=3306"`
        Username string       `env:"USERNAME,default=root"`
        Password string       `env:"PASSWORD,required"`
        Database string       `env:"NAME"`
        Nested   NestedConfig `env:""`
}

type Config struct {
        Debug     bool           `env:"DEBUG"`
        Port      string         `env:"PORT,default=8080"`
        RedisHost []string       `env:"REDIS_HOST|REDIS_HOSTS,default=localhost:6379"`
        RedisMode RedisMode      `env:"REDIS_MODE,default=standalone"`
        Database  DatabaseConfig `env:"DATABASE"`
}
```

I expect this, because I can use the same nested struct more than once in a struct

**Comment by ccoVeille** [comment]
Instead of calling env.Set and ignoring the error you should do that

```go
func setEnvForTest(t *testing.T, name string, value string) {
      err := Set(name, value)
      if err != nil {
           t.Fatalf("setting env variable %s with %q: %v", name, value, err
      }

      t.Cleanup(func () {
           err = Unset(name) // clean after the test
           if err  != nil {
                t.Fatalf("unsetting env variable %s: %v", name, err
            }
      })
}
```

**Comment by syntaqx** [comment]
> Let me start
> 
> I don't expect a lib to proxify `os` package
> 
> I would remove all this
> 
> ```go
> // Set sets an environment variable.
> func Set(key, value string) error {
>         return os.Setenv(key, value)
> }
> 
> // Unset unsets an environment variable.
> func Unset(key string) error {
>         return os.Unsetenv(key)
> }
> 
> // Lookup returns the value of an environment variable and a boolean indicating
> // whether the variable is present in the environment.
> func Lookup(key string) (string, bool) {
>         return os.LookupEnv(key)
> }
> 
> // Get returns the value of an environment variable.
> func Get(key string) string {
>         return os.Getenv(key)
> }
> ```

I disagree on this, I quite like working with the package the same way throughout the package code, and application code, but there's nothing _requiring_ usage of these outside of the package.

> I disagree with your *WithFallback helper.
> 
> Returning the fallback method when the env variable is expected, so you should always use Lookup, then call the method you are fallback.
> 
> Bit I disagree with the fallback on any other error.
> 
> Is someone provide "foo" in an env variable that is supposed to be a float, the code should know there is an error
> 
> You should always return an error in the methods signature
> 
> You may return the fallback value on error, but there should be a clear error returned

I can look at this a bit further.

> About this
> 
> ```go
> type DatabaseConfig struct {
>         Host     string       `env:"DATABASE_HOST,default=localhost"`
>         Port     int          `env:"DATABASE_PORT|DB_PORT,fallback=3306"`
>         Username string       `env:"DATABASE_USERNAME,default=root"`
>         Password string       `env:"DATABASE_PASSWORD,required"`
>         Database string       `env:"DATABASE_NAME"`
>         Nested   NestedConfig `env:""`
> }
> 
> type Config struct {
>         Debug     bool           `env:"DEBUG"`
>         Port      string         `env:"PORT,default=8080"`
>         RedisHost []string       `env:"REDIS_HOST|REDIS_HOSTS,default=localhost:6379"`
>         RedisMode RedisMode      `env:"REDIS_MODE,default=standalone"`
>         Database  DatabaseConfig `env:""`
> }
> ```
> 
> I would expect the config to define the database prefix
> 
> ```go
> type DatabaseConfig struct {
>         Host     string       `env:"HOST,default=localhost"`
>         Port     int          `env:"PORT|DB_PORT,fallback=3306"`
>         Username string       `env:"USERNAME,default=root"`
>         Password string       `env:"PASSWORD,required"`
>         Database string       `env:"NAME"`
>         Nested   NestedConfig `env:""`
> }
> 
> type Config struct {
>         Debug     bool           `env:"DEBUG"`
>         Port      string         `env:"PORT,default=8080"`
>         RedisHost []string       `env:"REDIS_HOST|REDIS_HOSTS,default=localhost:6379"`
>         RedisMode RedisMode      `env:"REDIS_MODE,default=standalone"`
>         Database  DatabaseConfig `env:"DATABASE"`
> }
> ```
> 
> I expect this, because I can use the same nested struct more than once in a struct

This is an interesting concept, I could see this being valuable.. let me think this through a bit. I like the idea of chaining, and with the usage of `env:"DATABASE"` it should be backwards compatible with the current implementation. I'll think on this.

**Comment by syntaqx** [comment]
I've opened a PR for Nested Prefixing.

However, in regards to:

> I disagree with your *WithFallback helper.
> 
> Returning the fallback method when the env variable is expected, so you should always use Lookup, then call the method you are fallback.
> 
> Bit I disagree with the fallback on any other error.
> 
> Is someone provide "foo" in an env variable that is supposed to be a float, the code should know there is an error
> 
> You should always return an error in the methods signature
> 
> You may return the fallback value on error, but there should be a clear error returned

So generally I'm in alignment with you on a lot of this, especially the `Lookup` part, but when looking at changing the signature I'm a little torn. Take this walkthrough for example:

```go
// Originally, code would exist as:
dbPort := os.Getenv("DATABASE_PORT")

// With `env`, you can simply drop-in a replacement of
dbPort := env.GetIntWithFallback("DATABASE_PORT", 3306)

// To support your usecase, it would require:
dbPort, err := env.GetIntWithFallback("DATABASE_PORT", 3306)
if err != nil { ... }
```

Which while I don't hate, it makes my package significantly less "drop-in" replacement for the `os.Getenv`signature, which I'm actively trying to match.

If someone were to normally do something like:
```go
port, ok := os.LookupEnv("PORT")
if !ok {
  port = "8080"
}
```

Even still, my signature changes from the `ok` boolean, to needing to handle an error.

Does this make sense where my hesitation comes from?

**Comment by ccoVeille** [comment]
> Even still, my signature changes from the ok boolean, to needing to handle an error.\n\nDoes this make sense where my hesitation comes from?

First of all, thanks for looking at my feedbacks,reply to them, and the changes you did via the PR

I get why you are hesitating.

But you also understand my point. I can understand you want them to do that.

But then, I would expect a clear warming about the usage of fallback method when data are invalid.

You added a comment in each method, but the readme should be clearer about the possible issue, and that's by design that you wanted that.

Otherwise, the methods comments could appear as a description of the code, like an IA autocomplete would generate.

**Comment by syntaqx** [comment]
I appreciate the feedback, it's always good to have eyes on things I make; And your suggestions are generally very helpful :)

I'm currently playing around with a change that I think makes this work better in my brain.

1. Changes `Get` to `val, err := env.Get("TEST")` signature, so it's not just a proxy call.
2. Introduces `error` signatures across most functions; A key function not having that is `GetWithFallback` as there's no real error condition here.

And playing with tests on it. I'll open a draft PR soon enough.

**Comment by ccoVeille** [comment]
Honestly, I'm unsure about these fallback helper, I think people will use the struct tag and the Unmarshall will throw an error if you are using a default value equal to "foo" for a float64/int, or if the value provided by the env variables are not compatible with the field type.

This is what you should make sure to cover in tests

**Comment by syntaqx** [comment]
Yes, the `Unmarshal` behaves that way, which is basically what convinced me it's probably ideal if the same value given to `Unmarshal`, which would return an error, also returns that error when you're retrieving it with `*WithFallback` methods.

I want the functions to behave consistently, so I think adding the `error` signature is probably the path forward.

**Comment by syntaqx** [comment]
I've opened #6 for feedback. Please continue any feedback in that PR, and open new issues separate from this one.
